#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 11 11:27:23 2018

@author: fred
"""
#personagem inicio, andando e pulando, paredes limitadas

import pygame
pygame.init()

isJump = False
jumpCount = 10


win = pygame.display.set_mode((500, 500))
pygame.display.set_caption("first game")

x = 50
y = 425
width = 40
height = 60
vel = 20

run = True
while run:
    pygame.time.delay(100)
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            run - False
    
    keys = pygame.key.get_pressed()
    if keys[pygame.K_LEFT] and x > vel:
        x -= vel 
    if keys[pygame.K_RIGHT] and x < 500 - width - vel:
        x += vel
    if not(isJump):
        if keys[pygame.K_UP] and y > vel:
            y -= vel
        if keys [pygame.K_DOWN] and y < 500 - height - vel:
            y += vel
        if keys[pygame.K_SPACE]:
            isJump = True 
    else:
          if jumpCount >=  -10:
              neq = 1
              if jumpCount < 0:
                  neq = -1
              y -= (jumpCount ** 2) * 0.5 * neq
              jumpCount -= 1
          else: 
              isJump = False
              jumpCount = 10
        
        
        
    win.fill((0, 0, 0))
    pygame.draw.rect(win,(225, 0, 0), (x, y, width, height))
    pygame.display.update()
pygame.quit()
